achievements:
  game_win:
    - tier: 1
      name: "Vencedor Iniciante (Tier I)"
      goal: 1
      material: DIAMOND_SWORD
      lore:
        - "§7Ganhe sua primeira partida."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 2
      name: "Campeão Ascendente (Tier II)"
      goal: 50
      material: GOLD_SWORD
      lore:
        - "§7Ganhe 50 partidas."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 3
      name: "Mestre Invicto (Tier III)"
      goal: 200
      material: IRON_SWORD
      lore:
        - "§7Ganhe 200 partidas."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"

  ranked_win:
    - tier: 1
      name: "Vitória de Estreia (Tier I)"
      goal: 1
      material: GOLD_BLOCK
      lore:
        - "§7Ganhe sua primeira partida"
        - "§cranqueada§7."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 2
      name: "Glória na Ranqueada (Tier II)"
      goal: 50
      material: EMERALD
      lore:
        - "§7Ganhe 50 partidas"
        - "§cranqueadas§7."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 3
      name: "Rei das Ranqueadas (Tier III)"
      goal: 200
      material: DIAMOND
      lore:
        - "§7Ganhe 200 partidas."
        - "§cranqueadas§7."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"

  game_defeat:
    - tier: 1
      name: "Sobrevivente (Tier I)"
      goal: 1
      material: WOOD_SWORD
      lore:
        - "§7Perca sua primeira partida."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 2
      name: "Resiliente (Tier II)"
      goal: 50
      material: STONE_SWORD
      lore:
        - "§7Perca 50 partidas."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 3
      name: "Implacável (Tier III)"
      goal: 100
      material: IRON_SWORD
      lore:
        - "§7Perca 100 partidas."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"

  ranked_defeat:
    - tier: 1
      name: "Derrotado Mas Não Vencido (Tier I)"
      goal: 1
      material: LEATHER_HELMET
      lore:
        - "§7Perca sua primeira partida"
        - "§cranqueada§7."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 2
      name: "Persistente (Tier II)"
      goal: 50
      material: IRON_HELMET
      lore:
        - "§7Perca 50 partidas"
        - "§cranqueadas§7."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 3
      name: "Coração Inabalável (Tier III)"
      goal: 100
      material: DIAMOND_HELMET
      lore:
        - "§7Perca 100 partidas"
        - "§cranqueadas§7."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"

  bed_broken:
    - tier: 1
      name: "Destruidor de Camas (Tier I)"
      goal: 1
      material: BED
      lore:
        - "§7Destrua sua primeira cama."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 2
      name: "Pesadelo de Camas (Tier II)"
      goal: 100
      material: BED
      lore:
        - "§7Destrua 100 camas."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 3
      name: "Aniquilador de Sonhos (Tier III)"
      goal: 250
      material: BED
      lore:
        - "§7Destrua 250 camas."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"

  games_played:
    - tier: 1
      name: "Jogador Novato (Tier I)"
      goal: 1
      material: BOOK
      lore:
        - "§7Jogue sua primeira partida."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 2
      name: "Veterano (Tier II)"
      goal: 150
      material: BOOK
      lore:
        - "§7Jogue 150 partidas."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 3
      name: "Lendário (Tier III)"
      goal: 300
      material: BOOK
      lore:
        - "§7Jogue 300 partidas."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"

  ranked_played:
    - tier: 1
      name: "Subindo no Pódio (Tier I)"
      goal: 1
      material: COMPASS
      lore:
        - "§7Jogue sua primeira partida"
        - "§cranqueada§7."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 2
      name: "Veterano da Arena (Tier II)"
      goal: 50
      material: IRON_DOOR
      lore:
        - "§7Jogue 50 partidas"
        - "§cranqueadas§7."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 3
      name: "Conhecido na Comunidade (Tier III)"
      goal: 150
      material: BANNER_RED
      lore:
        - "§7Jogue 150 partidas"
        - "§cranqueadas§7."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"

  kill:
    - tier: 1
      name: "Assassino Iniciante (Tier I)"
      goal: 1
      material: IRON_SWORD
      lore:
        - "§7Faça sua primeira kill."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 2
      name: "Caçador Experiente (Tier II)"
      goal: 250
      material: GOLD_SWORD
      lore:
        - "§7Faça 250 kills."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 3
      name: "Executor Implacável (Tier III)"
      goal: 500
      material: DIAMOND_SWORD
      lore:
        - "§7Faça 500 kills."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"

  final_kill:
    - tier: 1
      name: "Executor Final (Tier I)"
      goal: 1
      material: IRON_AXE
      lore:
        - "§7Faça sua primeira kill final."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 2
      name: "Açougueiro (Tier II)"
      goal: 100
      material: GOLD_AXE
      lore:
        - "§7Faça 100 kills finais."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 3
      name: "Ceifador Supremo (Tier III)"
      goal: 300
      material: DIAMOND_AXE
      lore:
        - "§7Faça 300 kills finais."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"

  shop_buy:
    - tier: 1
      name: "Comprador Cauteloso (Tier I)"
      goal: 1
      material: GOLD_INGOT
      lore:
        - "§7Faça sua primeira compra na loja."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 2
      name: "Cliente Fiel (Tier II)"
      goal: 200
      material: GOLD_INGOT
      lore:
        - "§7Faça 200 compras na loja."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 3
      name: "Magnata (Tier III)"
      goal: 1000
      material: DIAMOND
      lore:
        - "§7Faça 1000 compras na loja."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"

  upgrade_buy:
    - tier: 1
      name: "Iniciante em Melhorias (Tier I)"
      goal: 1
      material: ANVIL
      lore:
        - "§7Compre sua primeira melhoria."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 2
      name: "Especialista em Melhorias (Tier II)"
      goal: 50
      material: ANVIL
      lore:
        - "§7Compre 50 melhorias."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
    - tier: 3
      name: "Mestre das Melhorias (Tier III)"
      goal: 100
      material: ANVIL
      lore:
        - "§7Compre 100 melhorias."
        - ""
        - "§7Progresso: §a{progress}"
        - "{status}"
